name: todo_list
description: A todo list app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  sqflite: ^1.3.2+3
  get_it: ^5.0.6
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  build_runner: ^1.11.1

flutter:
  uses-material-design: true
